services:
  ErdmannFreunde\ContaoGridBundle\GridClasses:
    public: true

  ErdmannFreunde\ContaoGridBundle\EventListener\AddGridClassesToContentListener:
    arguments: ['@request_stack', '@contao.routing.scope_matcher']
    public: true

  ErdmannFreunde\ContaoGridBundle\EventListener\DataContainer\GridClassesOptionsListener:
    arguments: ['@ErdmannFreunde\ContaoGridBundle\GridClasses']
    public: true

  ErdmannFreunde\ContaoGridBundle\EventListener\DataContainer\GridColsOptionsListener:
    arguments: ['@ErdmannFreunde\ContaoGridBundle\GridClasses']
    public: true
